spring.application.name=servlet

# Tomcat HTTP/1.1 ???? ?? ?? ??? ?? ????(TRACE ??) ??
# (HTTP ??/?? ??, ??? ??/?? ?? ? ???? ?? ??? ???)
logging.level.org.apache.coyote.http11=trace


# ????? ???? ? ?? ??? ??(/WEB-INF/views/)? ???(.jsp)? ???? ???? ??
# ?: "members" ?? -> "/WEB-INF/views/members.jsp" ?? ??

#   @RequestMapping("/members")
#   public String members() {
#       return "members"; // ??? ? ?? ??
#   }

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

